import { GoogleGenAI } from '@google/genai';
import type { GenerateVideoParams } from '../types.js';
import { GenerationMode } from '../types.js';

function getAI(apiKey: string) {
  return new GoogleGenAI({ apiKey });
}

// Generate an image using any Gemini or Imagen model, with optional reference images
export async function generateImage(
  prompt: string,
  apiKey: string,
  model: string,
  aspectRatio = '16:9',
  referenceImages?: { buffer: Buffer; mimeType: string }[]
): Promise<{ buffer: Buffer; mimeType: string }> {
  const ai = getAI(apiKey);

  if (model.startsWith('imagen-')) {
    // Imagen API (no reference images support in basic API)
    const response = await (ai.models as any).generateImages({
      model,
      prompt,
      config: { numberOfImages: 1, aspectRatio },
    });
    const imageBytes = response?.generatedImages?.[0]?.image?.imageBytes;
    if (!imageBytes) throw new Error('No image generated by Imagen.');
    return { buffer: Buffer.from(imageBytes, 'base64'), mimeType: 'image/png' };
  }

  // Gemini image model — supports reference images as inlineData parts
  const parts: any[] = [];
  for (const ref of referenceImages || []) {
    parts.push({ inlineData: { data: ref.buffer.toString('base64'), mimeType: ref.mimeType } });
  }
  parts.push({ text: prompt });

  const response = await ai.models.generateContent({
    model,
    contents: { parts },
    config: { imageConfig: { aspectRatio } },
  } as any);

  for (const part of response.candidates?.[0]?.content?.parts || []) {
    if ((part as any).inlineData) {
      const { data, mimeType } = (part as any).inlineData;
      return { buffer: Buffer.from(data, 'base64'), mimeType: mimeType || 'image/png' };
    }
  }
  throw new Error('No image generated by Gemini.');
}

// Generate a single image using the default model (used for scene frame generation)
export async function generateImageFromPrompt(
  prompt: string,
  apiKey: string,
  aspectRatio = '16:9'
): Promise<{ buffer: Buffer; mimeType: string }> {
  const ai = getAI(apiKey);
  const response = await ai.models.generateContent({
    model: 'gemini-3.1-flash-image-preview',
    contents: { parts: [{ text: prompt }] },
    config: {
      imageConfig: { aspectRatio },
    },
  } as any);

  for (const part of response.candidates?.[0]?.content?.parts || []) {
    if ((part as any).inlineData) {
      const inlineData = (part as any).inlineData;
      const buffer = Buffer.from(inlineData.data, 'base64');
      const mimeType: string = inlineData.mimeType || 'image/png';
      return { buffer, mimeType };
    }
  }
  throw new Error('No image generated by Gemini.');
}

// Enhance a user prompt using Gemini text generation
export async function enhancePrompt(prompt: string, type: string, apiKey: string): Promise<string> {
  const ai = getAI(apiKey);
  const isImage = type === 'text-to-image';

  const metaPrompt = isImage
    ? `You are an expert AI image prompt engineer. Enhance the user's prompt for AI image generation.

Rules:
- Preserve the original subject and intent completely
- Add camera/lens details (e.g., "shot on Canon EOS R5, 85mm f/1.4 prime lens, shallow depth of field, subtle bokeh")
- Add lighting (e.g., "golden hour lighting", "soft studio rim light", "Rembrandt lighting setup")
- Add quality descriptors (e.g., "8K, RAW photo, photorealistic, hyperdetailed, ultra-sharp")
- Add composition (e.g., "rule of thirds framing", "cinematic composition", "professional photography")
- Output ONLY the enhanced prompt — no explanations, no quotes, no preamble
- Keep it to 2-3 sentences maximum

User prompt: ${prompt}`
    : `You are an expert AI video prompt engineer. Enhance the user's prompt for AI video generation.

Rules:
- Preserve the original subject and intent completely
- Add camera movement (e.g., "slow cinematic dolly push-in", "sweeping crane shot", "smooth handheld tracking")
- Add lens details (e.g., "wide-angle 24mm anamorphic lens", "telephoto 135mm", "anamorphic lens flares")
- Add cinematic look (e.g., "cinematic color grade", "subtle film grain", "dramatic chiaroscuro lighting")
- Add quality (e.g., "4K cinematic quality", "ultra-detailed", "professional cinematography")
- Output ONLY the enhanced prompt — no explanations, no quotes, no preamble
- Keep it to 2-3 sentences maximum

User prompt: ${prompt}`;

  let response: any;
  try {
    response = await ai.models.generateContent({
      model: 'gemini-3.1-flash-lite-preview',
      contents: { parts: [{ text: metaPrompt }] },
    } as any);
  } catch (sdkErr: any) {
    console.error('[enhancePrompt] SDK error:', sdkErr?.message ?? sdkErr);
    throw new Error(sdkErr?.message ?? 'Gemini SDK error');
  }

  // Try multiple extraction paths (SDK version differences)
  const enhanced =
    response?.text?.trim() ||
    response?.candidates?.[0]?.content?.parts?.find((p: any) => p.text)?.text?.trim() ||
    response?.candidates?.[0]?.content?.parts?.[0]?.text?.trim();

  console.log('[enhancePrompt] result length:', enhanced?.length ?? 0);
  if (!enhanced) throw new Error('No enhanced prompt returned by model');
  return enhanced;
}

export async function generateScript(ideasNotes: string, apiKey: string): Promise<string> {
  const ai = getAI(apiKey);

  const metaPrompt = `You are a professional video scriptwriter. Based on the following ideas and notes, write a complete, engaging video script. Include narration text, tone directions, and pacing notes. Format it clearly with sections (Hook, Main Content, CTA, etc.) where appropriate.

Ideas and Notes:
${ideasNotes}

Return only the script text — no extra commentary, no preamble.`;

  let response: any;
  try {
    response = await ai.models.generateContent({
      model: 'gemini-2.0-flash-lite',
      contents: { parts: [{ text: metaPrompt }] },
    } as any);
  } catch (sdkErr: any) {
    console.error('[generateScript] SDK error:', sdkErr?.message ?? sdkErr);
    throw new Error(sdkErr?.message ?? 'Gemini SDK error');
  }

  const script =
    response?.text?.trim() ||
    response?.candidates?.[0]?.content?.parts?.find((p: any) => p.text)?.text?.trim() ||
    response?.candidates?.[0]?.content?.parts?.[0]?.text?.trim();

  console.log('[generateScript] result length:', script?.length ?? 0);
  if (!script) throw new Error('No script returned by model');
  return script;
}

// Enforce Veo API constraints before calling the API.
// Returns sanitized { resolution, duration, generateSound }.
function clampVideoParams(
  model: string,
  resolution: string,
  duration: string,
  generateSound: boolean,
  mode: GenerationMode
): { resolution: string; duration: number; withAudio: boolean } {
  const isVeo2 = model.includes('veo-2');

  // Veo 2: 720p only, durations {5,6,8}, no audio
  if (isVeo2) {
    const veo2Durations = [5, 6, 8];
    let dur = parseInt(duration);
    if (!veo2Durations.includes(dur)) dur = 8;
    return { resolution: '720p', duration: dur, withAudio: false };
  }

  // Veo 3.1 family: durations {4,6,8}
  const veo31Durations = [4, 6, 8];
  let dur = parseInt(duration);
  if (!veo31Durations.includes(dur)) dur = 8;

  // 1080p, 4k, or frames/references mode → must be 8s
  const lockedTo8 =
    resolution === '1080p' ||
    resolution === '4k' ||
    mode === GenerationMode.FRAMES_TO_VIDEO ||
    mode === GenerationMode.REFERENCES_TO_VIDEO;
  if (lockedTo8) dur = 8;

  return { resolution, duration: dur, withAudio: generateSound };
}

// Generate a video for a scene, return video Buffer
export async function generateVideoForScene(params: GenerateVideoParams, apiKey: string, retries = 3): Promise<Buffer> {
  console.log(`[gemini] generateVideoForScene start | model=${params.model} mode=${params.mode} resolution=${params.resolution} duration=${params.duration} aspect=${params.aspectRatio} audio=${params.generateSound} hasStartFrame=${!!params.startFrameBuffer} hasEndFrame=${!!params.endFrameBuffer}`);
  for (let attempt = 0; attempt < retries; attempt++) {
    try {
      if (attempt > 0) console.log(`[gemini] attempt ${attempt + 1}/${retries}`);
      return await _generateVideoForScene(params, apiKey);
    } catch (err: any) {
      const is429 = err?.status === 429 || err?.message?.includes('429') || err?.message?.includes('RESOURCE_EXHAUSTED');
      if (is429 && attempt < retries - 1) {
        const waitMs = Math.pow(2, attempt) * 15000; // 15s, 30s
        console.log(`[gemini] rate limit hit, waiting ${waitMs / 1000}s before retry ${attempt + 1}/${retries - 1}...`);
        await new Promise(r => setTimeout(r, waitMs));
      } else {
        console.error(`[gemini] generateVideoForScene failed after ${attempt + 1} attempt(s): ${err?.message}`);
        if (is429) throw new Error('Quota da API Gemini esgotada. Aguarde alguns minutos (RPM) ou até amanhã (RPD diário) e tente novamente.');
        throw err;
      }
    }
  }
  throw new Error('Max retries exceeded');
}

async function _generateVideoForScene(params: GenerateVideoParams, apiKey: string): Promise<Buffer> {
  const ai = getAI(apiKey);

  // Apply model-specific constraints before calling the API
  const clamped = clampVideoParams(
    params.model,
    params.resolution,
    params.duration,
    params.generateSound ?? false,
    params.mode
  );

  console.log(`[gemini] clamped params | resolution=${clamped.resolution} duration=${clamped.duration}s audio=${clamped.withAudio}`);

  const config: any = {
    numberOfVideos: 1,
    resolution: clamped.resolution,
    durationSeconds: clamped.duration,
    aspectRatio: params.aspectRatio,
  };

  if (clamped.withAudio) {
    config.generateAudio = true;
  }

  const payload: any = {
    model: params.model,
    prompt: params.prompt,
    config,
  };

  if (params.mode === GenerationMode.FRAMES_TO_VIDEO) {
    if (params.startFrameBuffer) {
      payload.image = {
        imageBytes: params.startFrameBuffer.toString('base64'),
        mimeType: params.startFrameMimeType || 'image/png',
      };
      console.log(`[gemini] startFrame attached | mimeType=${params.startFrameMimeType} size=${params.startFrameBuffer.length} bytes`);
    }
    if (params.endFrameBuffer) {
      payload.config.lastFrame = {
        imageBytes: params.endFrameBuffer.toString('base64'),
        mimeType: params.endFrameMimeType || 'image/png',
      };
      console.log(`[gemini] endFrame (lastFrame) attached | mimeType=${params.endFrameMimeType} size=${params.endFrameBuffer.length} bytes`);
    }
  }

  console.log(`[gemini] calling ai.models.generateVideos | model=${payload.model} prompt="${params.prompt.slice(0, 80)}..."`);
  const t0 = Date.now();
  let operation = await ai.models.generateVideos(payload);
  console.log(`[gemini] operation created | name=${(operation as any).name ?? 'unknown'} done=${operation.done} (${Date.now() - t0}ms)`);

  let pollCount = 0;
  while (!operation.done) {
    pollCount++;
    const elapsed = Math.round((Date.now() - t0) / 1000);
    console.log(`[gemini] polling operation | poll #${pollCount} elapsed=${elapsed}s done=${operation.done}`);
    await new Promise(r => setTimeout(r, 30000));
    operation = await (ai.operations as any).getVideosOperation({ operation });
  }

  const totalElapsed = Math.round((Date.now() - t0) / 1000);
  console.log(`[gemini] operation complete | polls=${pollCount} totalElapsed=${totalElapsed}s`);

  // Check for operation-level error (e.g. quota exceeded, policy rejection)
  const opError = (operation as any).error;
  if (opError) {
    console.error('[gemini] operation returned error:', JSON.stringify(opError));
    throw new Error(`Video generation failed: ${opError.message || JSON.stringify(opError)}`);
  }

  const opResponse = operation?.response as any;
  // @google/genai SDK may use either `generatedVideos` or `videos` depending on version
  const videos: any[] = opResponse?.generatedVideos ?? opResponse?.videos ?? [];
  console.log(`[gemini] response received | videosCount=${videos.length} responseKeys=${Object.keys(opResponse ?? {}).join(',')}`);

  if (!videos.length) {
    console.error('[gemini] operation completed with no videos. Full response:', JSON.stringify(opResponse));
    throw new Error('No videos generated. The prompt or images may have been filtered by the API safety policy.');
  }

  const videoUri = videos[0]?.video?.uri;
  if (!videoUri) {
    console.error('[gemini] no URI in video response:', JSON.stringify(videos[0]));
    throw new Error('Generated video has no URI. Response: ' + JSON.stringify(videos[0]));
  }

  console.log(`[gemini] fetching video from storage | uri=${videoUri.slice(0, 80)}...`);
  const url = decodeURIComponent(videoUri);
  const res = await fetch(`${url}&key=${apiKey}`);
  console.log(`[gemini] video fetch response | status=${res.status} contentType=${res.headers.get('content-type')}`);
  if (!res.ok) throw new Error(`Failed to fetch video: ${res.status} ${res.statusText}`);

  const arrayBuffer = await res.arrayBuffer();
  console.log(`[gemini] video downloaded | size=${arrayBuffer.byteLength} bytes (${(arrayBuffer.byteLength / 1024 / 1024).toFixed(1)} MB)`);
  return Buffer.from(arrayBuffer);
}
